# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='岗位名称')),
                ('description', models.TextField(verbose_name='岗位描述')),
                ('requirement', models.TextField(verbose_name='任职要求')),
                ('location', models.CharField(max_length=20, verbose_name='工作地点')),
                ('salary', models.CharField(max_length=20, verbose_name='薪资范围')),
                ('is_on', models.BooleanField(default=True, verbose_name='启用')),
                ('comment', models.TextField(verbose_name='备注')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=20, verbose_name='Name')),
                ('name_cn', models.CharField(max_length=20, verbose_name='姓名')),
                ('department', models.TextField(max_length=20, verbose_name='部门')),
                ('email', models.EmailField(max_length=254)),
                ('cellphone', models.CharField(max_length=20, verbose_name='手机')),
                ('is_on', models.BooleanField(default=True, verbose_name='在职')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='住址')),
                ('qq', models.CharField(blank=True, max_length=20, verbose_name='QQ')),
                ('wechat', models.CharField(blank=True, max_length=20, verbose_name='微信')),
                ('resume', models.FileField(blank=True, upload_to='', verbose_name='简历')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Position', verbose_name='职位')),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
    ]
