# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20170905_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.IntegerField(choices=[(0, '财务'), (1, '服务'), (2, '销售'), (3, '人事')], verbose_name='部门'),
        ),
    ]
